### ISSUE TITLE
DebitNote spam even when no tasks are running

### ISSUE THREAD

**Issue by mbenke** [golemfactory/yagna-triage#132]
Despite no tasks running (last activity finished 8h earlier)  yagna is still spamming 
```
DebitNote [0xa96d3f3e177687fb0b5f990d5c4000923b49430b] received from node [...] 
```
(many different node ids)  

yagna is also trying (and failing) to terminate agreements: 

```
WARN  ya_market::negotiation::common] Couldn't terminate agreement. id: R-8aaea8810c38e490fb785f2939fbac0e107c4221e2f3e72ff163b46bfef65952, e: Can't update Agreement state from Terminated to Terminated.
```

Logs from yesterday (tasks running): `golem@88.99.139.166:logs/yagna-1624276417-qQ2_xVKlmSPHE6wCLJaXoQ.log.gz` (yapapi)
`golem@88.99.139.166:logs/yagna_r2021-06-21_00-00-00.log.gz `(yagna)
Yagna log  from today (no tasks running):  `golem@88.99.139.166:logs/yagna210622-1.log.gz`

database backup available upon request.

While no tasks are running, this is merely an annoyance (and an unnecessary strain on our network), but while running tasks, this also puts additional strain on yapapi which has to process the spam events and it seems sometimes to have trouble managing valid payment events (I reckon about 5-10 spam events per one valid event)

**Comment by nieznanysprawiciel** [comment]
I'm taking this bug to Core board.
@mbenke Please estimate impact and severity

**Comment by mbenke** [comment]
> @mbenke Please estimate impact and severity

@nieznanysprawiciel it is hard to estimate right now, the question is if the spam is a problem for the network: if it is so, than it is a major thing, affecting all users. Otherwise it's a minor problem affecting big requestors only (is there more than one?)

**Comment by nieznanysprawiciel** [comment]
Problems with terminating Agreements are due  to the fact, that this Agreement was terminated by Provider long ago, because Requestor was unreachable for too long period of time.

This is AgreementTerminatedEvent in database:
```30253|R-8aaea8810c38e490fb785f2939fbac0e107c4221e2f3e72ff163b46bfef65952|Terminated|2021-06-18 06:52:53.284145921|P|{"message":"Requestor is unreachable more than 4m","golem.provider.code":"RequestorUnreachable"}|```

Termination was processed `2021-06-18 06:52:53`. It is long before first timestamp in the log you provided. Does it mean, that Requestor was running for few days without restart? On the other side I can't see any attempts to terminate Agreement in yapapi logs.

I'm still investigating DebitNotes spam

**Comment by mbenke** [comment]
@nieznanysprawiciel what do you mean by "Requestor was running for few days without restart?" If you mean the process, then yes, it's a long running process. If you mean Executor instance then no, a fresh instance is created for every batch that runs for about 2 hours.

**Comment by nieznanysprawiciel** [comment]
I mean that something was continuously trying to terminate this Agreement for a few days. I'm wondering if old Executor instances can do this, even if new instances are already created...

**Comment by mbenke** [comment]
I see these `Couldn't terminate agreement.` messages in yagna output even when the requestor is not running.

**Comment by nieznanysprawiciel** [comment]
Ok, it's more interesting. It seems Provider is terminating Agreement, not Requestor.

I have suspicion, that Providers are timeouting on calls to `terminate_agreement` and `send_debit_note`.
On Requestor side the call is executed correctly. In this case they would retry these calls in infinity.

I can't confirm this suspicion, since that was mainnet task and I can't have any logs

**Comment by nieznanysprawiciel** [comment]
Since we don't have enough information and it doesn't seem critical from Requestor perspective, we postpone this bug for `beta.2.patch.3`

**Comment by maaktweluit** [comment]
We need to monitor this issue now the network has improved with patch 0.7.2

**Comment by nieznanysprawiciel** [comment]
It seems problem doesn't appear anymore
