### ISSUE TITLE
Yacat batch timeout

### ISSUE THREAD

**Issue by maaktweluit** [golemfactory/yagna-triage#33]
Gert-Jan - Mac python 3.6 Yacat batch timeout

    ```jsx
    [2021-01-14 12:59:18,019 INFO yapapi.summary] Task sent to provider 'reqc.4', task data: None
    [2021-01-14 13:00:18,955 WARNING yapapi.summary] Activity failed on provider 'reqc.4', reason: BatchTimeoutError()
    ```

    GJ:

    [yacat-debug.log](https://s3-us-west-2.amazonaws.com/secure.notion-static.com/17e765e8-e247-4f2a-95be-a7962227671c/yacat-debug.log)

    mf - Ubuntu 20.04.1 LTS / Python 3.8.5 yacat BatchTimeoutError

    [yacat-debug.log](https://s3-us-west-2.amazonaws.com/secure.notion-static.com/a0576f12-4bab-4349-8611-00aa274b9318/yacat-debug.log)

    2rec: same here for both: mac 10.15.7 & ubuntu 18.04.4

    [yacat-debug-ubuntu-18.04.4.log](https://s3-us-west-2.amazonaws.com/secure.notion-static.com/e79e012c-c8c7-4b80-9c7d-debfd98ce36f/yacat-debug.log)

    [yacat-debug-mac-10.15.7.log](https://s3-us-west-2.amazonaws.com/secure.notion-static.com/3ed5ff80-e68c-42fa-815c-014fee542fed/yacat-debug.log)

magda - Win10 Pro. python 3.8.6:  

[yacat-debug.log](https://s3-us-west-2.amazonaws.com/secure.notion-static.com/a3d24355-faf7-4c41-bed4-5dbe71b3a342/yacat-debug.log)

Pawel

[yacat-debug.log](https://s3-us-west-2.amazonaws.com/secure.notion-static.com/916a9afa-15a5-418d-8cc2-3dc7529ae516/yacat-debug.log)

**Comment by azawlocki** [comment]
This test was run with the batch timeout set to 1 minute for the first call to `ctx.commit()` in `yacat.py`. 1 minute may be not enough, especially if the provider needs to download the VM image first.

Since the time of the test, the timeout has been increased to 10 minutes (https://github.com/golemfactory/yapapi/commit/98d340be94a9e731d9cb58265c816db1b735bd22#diff-c8b6a3c7266f69cbe549075f8a07b04c83df00b960b08590991c8e1d8123be44).
