### ISSUE TITLE
waitForApproval 408

### ISSUE THREAD

**Issue by maaktweluit** [golemfactory/yagna-triage#59]
ederenn - Win 10+js  - ApiException Error: Request failed with status code 408 attach `blender-yapapi.log`)

```
    2021-02-09 12:36:10 [yajsapi] debug: waitForApproval(45e788b70621c90bc017c9ac5e6a2f655afe4277e13a363bf4e9a729d6924aad) raised ApiException Error: Request failed with status code 408
    Done in 96.19s.
```
[yagna_rCURRENT.log](https://github.com/golemfactory/yagna-triage/files/5951264/yagna_rCURRENT.log)
[yajsapi.log](https://github.com/golemfactory/yagna-triage/files/5951265/yajsapi.log)
[market.db.txt](https://github.com/golemfactory/yagna-triage/files/5951273/market.db.txt)

**Comment by tworec** [comment]
https://yastats.golem.network/explore?orgId=1&left=%5B%22now-1h%22,%22now%22,%22Loki%22,%7B%22expr%22:%22%7Bjob%3D%5C%22devnet-alpha.4%5C%22%7D%20%7C%3D%20%5C%2245e788b70621c90bc017c9ac5e6a2f655afe4277e13a363bf4e9a729d6924aad%5C%22%22%7D%5D
![image](https://user-images.githubusercontent.com/12720209/107362797-86fb5d80-6ad9-11eb-9991-5c3f62e94d63.png)

This is legit `408` as Provider has no capacity at the moment, and rejected agreement.
Market Service is not implementing `RejectAgreement` operation, so Requestor will never get this information, and that's why yaXapi cannot present it to the user. In the next releases it will be properly communicated to our users.
